export const ICON_CATEGORIES = [
  { id: 'restaurant', label: { en: 'Restaurant', ar: 'مطعم', fa: 'رستوران' } },
  { id: 'retail', label: { en: 'Retail / Supermarket', ar: 'تجزئة / سوبر ماركت', fa: 'خرده فروشی / سوپرمارکت' } },
  { id: 'inventory', label: { en: 'Inventory', ar: 'المخزون', fa: 'انبار' } },
  { id: 'finance', label: { en: 'Finance', ar: 'المالية', fa: 'امور مالی' } },
  { id: 'production', label: { en: 'Production', ar: 'الإنتاج', fa: 'تولید' } },
  { id: 'general', label: { en: 'General', ar: 'عام', fa: 'عمومی' } },
];

export const ENTERPRISE_ICONS = [
  // Restaurant
  { name: 'Soup', category: 'restaurant', labels: { en: ['Rice', 'Soup', 'Bukhari Rice', 'Kabsa'], ar: ['أرز', 'شوربة', 'أرز بخاري', 'كبسة'], fa: ['برنج', 'سوپ', 'برنج بخاری', 'کبسه'] } },
  { name: 'Drumstick', category: 'restaurant', labels: { en: ['Chicken', 'Poultry'], ar: ['دجاج'], fa: ['مرغ'] } },
  { name: 'Flame', category: 'restaurant', labels: { en: ['Grill', 'BBQ', 'Fire'], ar: ['شواء', 'نار'], fa: ['گریل', 'کباب', 'آتش'] } },
  { name: 'Ham', category: 'restaurant', labels: { en: ['Burger', 'Meat'], ar: ['برجر', 'لحم'], fa: ['برگر', 'گوشت'] } },
  { name: 'Pizza', category: 'restaurant', labels: { en: ['Pizza'], ar: ['بيتزا'], fa: ['پیتزا'] } },
  { name: 'Sandwich', category: 'restaurant', labels: { en: ['Shawarma', 'Sandwich', 'Wrap'], ar: ['شاورما', 'ساندوتش'], fa: ['شاورما', 'ساندویچ'] } },
  { name: 'Fish', category: 'restaurant', labels: { en: ['Seafood', 'Fish', 'Shrimp'], ar: ['مأكولات بحرية', 'سمك', 'روبيان'], fa: ['غذای دریایی', 'ماهی', 'میگو'] } },
  { name: 'Beef', category: 'restaurant', labels: { en: ['Steak', 'Meat'], ar: ['ستيك', 'لحم'], fa: ['استیک', 'گوشت'] } },
  { name: 'Salad', category: 'restaurant', labels: { en: ['Salad', 'Vegetables'], ar: ['سلطة', 'خضروات'], fa: ['سالاد', 'سبزیجات'] } },
  { name: 'Utensils', category: 'restaurant', labels: { en: ['Pasta', 'Lunch', 'Dinner', 'Dine In'], ar: ['باستا', 'غداء', 'عشاء', 'تناول الطعام'], fa: ['پاستا', 'ناهار', 'شام', 'صرف در محل'] } },
  { name: 'IceCream', category: 'restaurant', labels: { en: ['Dessert', 'Ice Cream'], ar: ['حلوى', 'آيس كريم'], fa: ['دسر', 'بستنی'] } },
  { name: 'Cake', category: 'restaurant', labels: { en: ['Cake', 'Bakery'], ar: ['كيك', 'مخبوزات'], fa: ['کیک', 'شیرینی'] } },
  { name: 'Coffee', category: 'restaurant', labels: { en: ['Coffee', 'Tea', 'Hot Drinks'], ar: ['قهوة', 'شاي', 'مشروبات ساخنة'], fa: ['قهوه', 'چای', 'نوشیدنی گرم'] } },
  { name: 'CupSoda', category: 'restaurant', labels: { en: ['Juice', 'Soft Drinks', 'Beverages'], ar: ['عصير', 'مشروبات غازية', 'مشروبات'], fa: ['آبمیوه', 'نوشابه', 'نوشیدنی'] } },
  { name: 'GlassWater', category: 'restaurant', labels: { en: ['Water'], ar: ['ماء'], fa: ['آب'] } },
  { name: 'Egg', category: 'restaurant', labels: { en: ['Breakfast'], ar: ['إفطار'], fa: ['صبحانه'] } },
  { name: 'Leaf', category: 'restaurant', labels: { en: ['Sauce', 'Spices', 'Herbs'], ar: ['صلصة', 'توابل', 'أعشاب'], fa: ['سس', 'ادویه', 'گیاهان'] } },
  { name: 'CookingPot', category: 'restaurant', labels: { en: ['Kitchen', 'Cooking'], ar: ['مطبخ', 'طبخ'], fa: ['آشپزخانه', 'پخت و پز'] } },
  { name: 'ChefHat', category: 'restaurant', labels: { en: ['Chef'], ar: ['شيف', 'طباخ'], fa: ['سرآشپز'] } },
  { name: 'BookOpen', category: 'restaurant', labels: { en: ['Recipe', 'Menu'], ar: ['وصفة', 'منيو', 'قائمة طعام'], fa: ['دستور پخت', 'منو'] } },
  { name: 'DollarSign', category: 'restaurant', labels: { en: ['Food Cost'], ar: ['تكلفة الطعام'], fa: ['هزینه غذا'] } },
  { name: 'Truck', category: 'restaurant', labels: { en: ['Delivery'], ar: ['توصيل'], fa: ['ارسال'] } },
  { name: 'ShoppingBag', category: 'restaurant', labels: { en: ['Take Away'], ar: ['سفري', 'تيك أوي'], fa: ['بیرون بر'] } },
  { name: 'Table', category: 'restaurant', labels: { en: ['Table'], ar: ['طاولة'], fa: ['میز'] } },

  // Retail
  { name: 'Apple', category: 'retail', labels: { en: ['Fruits'], ar: ['فواكه'], fa: ['میوه جات'] } },
  { name: 'LeafyGreen', category: 'retail', labels: { en: ['Vegetables'], ar: ['خضروات'], fa: ['سبزیجات'] } },
  { name: 'Snowflake', category: 'retail', labels: { en: ['Frozen Food'], ar: ['طعام مجمد'], fa: ['غذای منجمد'] } },
  { name: 'Milk', category: 'retail', labels: { en: ['Dairy', 'Milk', 'Cheese', 'Butter'], ar: ['ألبان', 'حليب', 'جبن', 'زبدة'], fa: ['لبنیات', 'شیر', 'پنیر', 'کره'] } },
  { name: 'Croissant', category: 'retail', labels: { en: ['Bakery', 'Bread'], ar: ['مخبوزات', 'خبز'], fa: ['نانوایی', 'نان'] } },
  { name: 'Candy', category: 'retail', labels: { en: ['Snacks', 'Candy', 'Chocolate'], ar: ['سناكس', 'حلويات', 'شوكولاتة'], fa: ['تنقلات', 'شیرینی', 'شکلات'] } },
  { name: 'Sparkles', category: 'retail', labels: { en: ['Cleaning', 'Detergent'], ar: ['تنظيف', 'منظفات'], fa: ['نظافت', 'شوینده'] } },
  { name: 'FileText', category: 'retail', labels: { en: ['Paper'], ar: ['ورق'], fa: ['کاغذ'] } },
  { name: 'Baby', category: 'retail', labels: { en: ['Baby Care'], ar: ['عناية بالطفل'], fa: ['مراقبت از کودک'] } },
  { name: 'Heart', category: 'retail', labels: { en: ['Personal Care'], ar: ['عناية شخصية'], fa: ['مراقبت شخصی'] } },
  { name: 'Pill', category: 'retail', labels: { en: ['Medicine'], ar: ['دواء'], fa: ['دارو'] } },
  { name: 'Dog', category: 'retail', labels: { en: ['Pet Food'], ar: ['طعام حيوانات'], fa: ['غذای حیوانات'] } },
  { name: 'Smartphone', category: 'retail', labels: { en: ['Electronics'], ar: ['إلكترونيات'], fa: ['الکترونیک'] } },
  { name: 'Shirt', category: 'retail', labels: { en: ['Clothing'], ar: ['ملابس'], fa: ['پوشاک'] } },
  { name: 'Pencil', category: 'retail', labels: { en: ['Stationery'], ar: ['قرطاسية'], fa: ['لوازم التحریر'] } },
  { name: 'Gamepad', category: 'retail', labels: { en: ['Toys'], ar: ['ألعاب'], fa: ['اسباب بازی'] } },
  { name: 'Home', category: 'retail', labels: { en: ['Home'], ar: ['منزل'], fa: ['خانه'] } },

  // Inventory
  { name: 'Warehouse', category: 'inventory', labels: { en: ['Warehouse'], ar: ['مستودع'], fa: ['انبار'] } },
  { name: 'Columns', category: 'inventory', labels: { en: ['Shelf'], ar: ['رف'], fa: ['قفسه'] } },
  { name: 'Box', category: 'inventory', labels: { en: ['Box', 'Raw Material'], ar: ['صندوق', 'مواد خام'], fa: ['جعبه', 'مواد اولیه'] } },
  { name: 'Package', category: 'inventory', labels: { en: ['Carton', 'Package', 'Packaging', 'Finished Goods'], ar: ['كرتون', 'طرد', 'تغليف', 'منتجات جاهزة'], fa: ['کارتن', 'بسته', 'بسته بندی', 'کالای نهایی'] } },
  { name: 'Layers', category: 'inventory', labels: { en: ['Pallet', 'Subcategory'], ar: ['طبلية', 'فئة فرعية'], fa: ['پالت', 'زیرمجموعه'] } },
  { name: 'Barcode', category: 'inventory', labels: { en: ['Barcode'], ar: ['باركود'], fa: ['بارکد'] } },
  { name: 'QrCode', category: 'inventory', labels: { en: ['QR Code'], ar: ['رمز QR'], fa: ['کد QR'] } },
  { name: 'Archive', category: 'inventory', labels: { en: ['Stock'], ar: ['مخزون'], fa: ['موجودی'] } },
  { name: 'AlertTriangle', category: 'inventory', labels: { en: ['Low Stock'], ar: ['مخزون منخفض'], fa: ['موجودی کم'] } },
  { name: 'XCircle', category: 'inventory', labels: { en: ['Out of Stock'], ar: ['نفذ المخزون'], fa: ['اتمام موجودی'] } },
  { name: 'ArrowLeftRight', category: 'inventory', labels: { en: ['Transfer'], ar: ['تحويل'], fa: ['انتقال'] } },
  { name: 'Download', category: 'inventory', labels: { en: ['Receiving'], ar: ['استلام'], fa: ['دریافت'] } },
  { name: 'Upload', category: 'inventory', labels: { en: ['Dispatch'], ar: ['إرسال'], fa: ['ارسال'] } },

  // Finance
  { name: 'Banknote', category: 'finance', labels: { en: ['Cash'], ar: ['نقد'], fa: ['نقد'] } },
  { name: 'Building2', category: 'finance', labels: { en: ['Bank'], ar: ['بنك'], fa: ['بانک'] } },
  { name: 'CreditCard', category: 'finance', labels: { en: ['Card', 'Credit'], ar: ['بطاقة', 'ائتمان'], fa: ['کارت', 'اعتبار'] } },
  { name: 'Wallet', category: 'finance', labels: { en: ['Wallet'], ar: ['محفظة'], fa: ['کیف پول'] } },
  { name: 'Receipt', category: 'finance', labels: { en: ['Receipt', 'Invoice'], ar: ['إيصال', 'فاتورة'], fa: ['رسید', 'فاکتور'] } },
  { name: 'ShoppingCart', category: 'finance', labels: { en: ['Purchase'], ar: ['شراء'], fa: ['خرید'] } },
  { name: 'TrendingUp', category: 'finance', labels: { en: ['Sales', 'Profit'], ar: ['مبيعات', 'ربح'], fa: ['فروش', 'سود'] } },
  { name: 'TrendingDown', category: 'finance', labels: { en: ['Expense'], ar: ['مصروف'], fa: ['هزینه'] } },
  { name: 'Percent', category: 'finance', labels: { en: ['Tax'], ar: ['ضريبة'], fa: ['مالیات'] } },
  { name: 'Tag', category: 'finance', labels: { en: ['Discount'], ar: ['خصم'], fa: ['تخفیف'] } },
  { name: 'Landmark', category: 'finance', labels: { en: ['Treasury'], ar: ['خزينة'], fa: ['خزانه'] } },
  { name: 'HandCoins', category: 'finance', labels: { en: ['Payment'], ar: ['دفع'], fa: ['پرداخت'] } },

  // Production
  { name: 'Factory', category: 'production', labels: { en: ['Factory'], ar: ['مصنع'], fa: ['کارخانه'] } },
  { name: 'Settings2', category: 'production', labels: { en: ['Machine'], ar: ['ماكينة'], fa: ['ماشین'] } },
  { name: 'Hammer', category: 'production', labels: { en: ['Production'], ar: ['إنتاج'], fa: ['تولید'] } },
  { name: 'Component', category: 'production', labels: { en: ['Assembly'], ar: ['تجميع'], fa: ['مونتاژ'] } },

  // General
  { name: 'Folder', category: 'general', labels: { en: ['Folder'], ar: ['مجلد'], fa: ['پوشه'] } },
  { name: 'Bookmark', category: 'general', labels: { en: ['Label'], ar: ['ملصق'], fa: ['برچسب'] } },
  { name: 'Grid', category: 'general', labels: { en: ['Category'], ar: ['فئة'], fa: ['دسته بندی'] } },
  { name: 'GitBranch', category: 'general', labels: { en: ['Branch'], ar: ['فرع'], fa: ['شعبه'] } },
  { name: 'Building', category: 'general', labels: { en: ['Company'], ar: ['شركة'], fa: ['شرکت'] } },
  { name: 'Users', category: 'general', labels: { en: ['Users', 'Employee'], ar: ['مستخدمين', 'موظف'], fa: ['کاربران', 'کارمند'] } },
  { name: 'User', category: 'general', labels: { en: ['Customer'], ar: ['عميل'], fa: ['مشتری'] } },
  { name: 'Settings', category: 'general', labels: { en: ['Settings'], ar: ['إعدادات'], fa: ['تنظیمات'] } },
  { name: 'FileBarChart', category: 'general', labels: { en: ['Reports'], ar: ['تقارير'], fa: ['گزارش ها'] } },
  { name: 'LayoutDashboard', category: 'general', labels: { en: ['Dashboard'], ar: ['لوحة التحكم'], fa: ['داشبورد'] } },
  { name: 'BarChart3', category: 'general', labels: { en: ['Analytics'], ar: ['تحليلات'], fa: ['تجزیه و تحلیل'] } },
  { name: 'Calendar', category: 'general', labels: { en: ['Calendar'], ar: ['تقويم'], fa: ['تقویم'] } },
  { name: 'Clock', category: 'general', labels: { en: ['Clock'], ar: ['ساعة'], fa: ['ساعت'] } },
  { name: 'Bell', category: 'general', labels: { en: ['Notification'], ar: ['تنبيه'], fa: ['اعلان'] } },
];
